version: '3.0'

services:
  grafana:
    container_name: 'datahub-json-datasource'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-main}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/datahub-json-datasource
      - ./provisioning:/etc/grafana/provisioning
    networks:
      - grafana-network

  mock-api:
    image: node:18-alpine
    container_name: mock-json-api
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./mock-api:/app
    command: node server.js
    stop_grace_period: 3s
    networks:
      - grafana-network

networks:
  grafana-network:
    driver: bridge
